### ISSUE TITLE
Working Yomichan search?

### ISSUE THREAD

**Issue by aehlke** [lingfeishengtian/CJE-Dictionary#1]
Hi, thanks for sharing your work. Is the Yomichan importing and searching working ok for you?

**Comment by lingfeishengtian** [comment]
I am not familiar with Yomichan.

**Comment by aehlke** [comment]
Oh I asked because I saw "YomichanFileParser.swift": https://github.com/lingfeishengtian/CJE-Dictionary/blob/031f98c3f2d3461bc68d2087d01ee3014fd93142/CJE%20Dictionary/DictionaryManager.swift#L2 and assumed you're working with Yomichan-format dictionary files ( https://foosoft.net/projects/yomichan/ )

**Comment by lingfeishengtian** [comment]
I understand where the confusion came from. The open source dictionary, JMDict, references yomichan, and I must've named a file incorrectly.
